### ISSUE TITLE
Doesn't work in iOS 13

### ISSUE THREAD

**Issue by Gargo** [DevYeom/YYBottomSheet#52]
Just tried simple code from your readme:
`Manually adding the rootViewController's view to the view hierarchy is no longer supported. Please allow UIWindow to add the rootViewController's view to the view hierarchy itself.`

**Comment by DevYeom** [comment]
Thanks a lot 😀
I updated for iOS 13
Please check [1.4.0](https://github.com/DevYeom/YYBottomSheet/releases/tag/1.4.0)
